version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: ./deploy/backend.Dockerfile
    restart: unless-stopped
    environment:
      - APP_ENV=prod
      - MAX_UPLOAD_MB=10
      - ORIGIN=http://${DOMAIN:-localhost}
    networks:
      - internal

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - internal

networks:
  internal:
    driver: bridge
